using System.Text;
using System.Xml.Linq;

namespace WizardTea.Generator.Parsers;

public abstract class BaseParser : IParser {
    public abstract void Parse();
    public abstract void Generate();

    protected BaseParser(XDocument xml) {
        Xml = xml;
    }

    public XDocument Xml { get; set; }

    protected static string Prelude() {
        var sb = new StringBuilder();

        sb.AppendLine("/// <auto-generated>");
        sb.AppendLine($"/// This file has been auto-generated by WizardTea v{Constants.GeneratorVersion.ToString()}.");
        sb.AppendLine("///");
        sb.AppendLine("/// Do not edit unless you know what you are doing.");
        sb.AppendLine("/// If there is an issue, file at https://github.com/glomdom/WizardTea/issues/");
        sb.AppendLine("/// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine();
        sb.AppendLine("namespace WizardTea;");
        
        return sb.ToString();
    }
}